# Generated by Django 3.0.2 on 2020-01-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolClass', models.CharField(max_length=20)),
                ('className', models.CharField(max_length=20)),
                ('schoolClassChinese', models.CharField(max_length=20)),
                ('seatNumber', models.CharField(max_length=20)),
                ('studentID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('identityCard', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=2)),
                ('birth_date', models.CharField(max_length=20)),
            ],
        ),
    ]
