# Generated by Django 3.0.2 on 2020-01-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=20)),
                ('timeSunday', models.CharField(max_length=20)),
                ('timeMonday', models.CharField(max_length=20)),
                ('timeTuesday', models.CharField(max_length=20)),
                ('timeWedensday', models.CharField(max_length=20)),
                ('timeThursday', models.CharField(max_length=20)),
                ('timeFriday', models.CharField(max_length=20)),
                ('timeSaturday', models.CharField(max_length=20)),
            ],
        ),
    ]
