# Generated by Django 3.0.2 on 2020-01-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timeFridayEnd',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timeMondayEnd',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timeSaturdayEnd',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timeSundayEnd',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timeThursdayEnd',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timeTuesdayEnd',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timeWedensdayEnd',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timeFriday',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timeMonday',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timeSaturday',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timeSunday',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timeThursday',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timeTuesday',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timeWedensday',
            field=models.TimeField(auto_now=True),
        ),
    ]
