# Generated by Django 3.0.2 on 2020-01-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200107_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
            ],
        ),
    ]
